add_lbug_test(node_insertion_deletion_test node_insertion_deletion_test.cpp)
add_lbug_test(compression_test compression_test.cpp compress_chunk_test.cpp)
add_lbug_test(column_chunk_metadata_test column_chunk_metadata_test.cpp)
add_lbug_test(local_hash_index_test local_hash_index_test.cpp)
add_lbug_test(buffer_manager_test buffer_manager_test.cpp)
add_lbug_test(rel_tests rel_scan_test.cpp rel_delete_test.cpp)
add_lbug_test(node_update_test node_update_test.cpp)

target_include_directories(compression_test PRIVATE ${PROJECT_SOURCE_DIR}/third_party/alp/include)

add_executable(string_chunk_scan_test string_chunk_scan_test.cpp)
target_link_libraries(string_chunk_scan_test PRIVATE GTEST_LIB lbug)
include(GoogleTest)
gtest_discover_tests(string_chunk_scan_test DISCOVERY_TIMEOUT 600 DISCOVERY_MODE PRE_TEST)

add_executable(input_validation_test input_validation_test.cpp)
target_link_libraries(input_validation_test PRIVATE GTEST_LIB lbug)
gtest_discover_tests(input_validation_test DISCOVERY_TIMEOUT 600 DISCOVERY_MODE PRE_TEST)
